export type FormData = {
  loanAmount: number;
  loanTerm: number;
  firstName: string;
  lastName: string;
  middleName: string;
  birthDate: string;
  phone: string;
  email: string;
  regAddress: string;
  actualAddress: string;
  sameAddress: boolean;
  workplace: string;
  position: string;
  monthlyIncome: string;
  passportPhoto: File | null;
  cardPhoto: File | null;
  paymentMethod: 'card' | 'sbp' | 'bank';
  cardNumber?: string;
  phoneForSbp?: string;
  sbpBank?: string;
  bankAccount?: string;
  bankName?: string;
  bankBik?: string;
  passportSeries?: string;
  passportNumber?: string;
};